### ISSUE TITLE
BDFL concept should go away

### ISSUE THREAD

**Issue by Jacob-Barhak** [openjournals/governance#4]
The idea of BDFL is not really proper. 

I understand that some people put a lot of effort into a topic and should get recognition, yet there are other ways to give it other than the BDFL title. 

Some organizations got the hint. 

I suggest open journals follows.

**Comment by arfon** [comment]
Quite possibly although in reality the BDFL (me) makes very few (any?) real decisions at the top level of Open Journals. We may change this in the future but right now I don't think this is a priority for us.

**Comment by Jacob-Barhak** [comment]
Sorry Arfon,

In that case this issue should stay open - no resolution was provided nor a
proper discussion on governance.

I was surprised to see this - organizations these days are stripping away
BDFL for good reasons.

If indeed you intend to change it in the future, leave the issue open to
indicate this intention.
